### ISSUE TITLE
Question about -dy and -dx

### ISSUE THREAD

**Issue by Modjular** [lens-biophotonics/ZetaStitcher#11]
![Screen Shot 2021-06-02 at 9 34 51 AM](https://user-images.githubusercontent.com/8238329/120836720-b74c8900-c51a-11eb-8063-b729d0c58386.png)

I have a question about `stitch-align`, and what it's actually doing under the hood.
I tested three different alignments: 

1. `--dx 300 --dy 300`
2. `--dx 150 --dy 150`
3. `--dx 50 --dy 50` 

and `--px-size-xy 0.91`

Why aren't the shifts the same? My assumption is that `--dx` is asking "How far, horizontally, from `x=0` (relative to the tile's nominal position) should we be searching?"

**Comment by gmazzamuto** [comment]
Hi, thanks for you interest in ZetaStitcher. First of all, let me tell you that I just made available a new release (v0.6.0); please upgrade to that one because it contains some important fixes.

Coming to your questions, I first need to make a clarification:`dx` and `dy` do not refer to horizontal and vertical search ranges. `dy` is the search range on the axis along which two tiles overlap (might be `X` or `Y`). `dx` is the search range on the axis which is orthogonal to the first one. So, for two tiles that touch each other horizontally, `dx` is actually vertical and `dy` horizontal. Whereas for two tiles that touch each other vertically, `dy` is vertical and `dx` horizontal. I like to think of `dy` and `dx` as the overlap direction and the transversal direction, respectively.

The positions and the shifts you are reading in the `stitch.yml` file are not final. They are referred to the cross-correlation maps that the software computes internally. If you make the search area bigger and the shifts are measured with respect to the top-left corner of the search area, the same point in the cross-correlation maps would have two different coordinates depending on how big the map is.

Hope this helps. I appreciate some feedback, please let me know if this software works for you.

**Comment by Modjular** [comment]
> Coming to your questions, I first need to make a clarification:`dx` and `dy` do not refer to horizontal and vertical search ranges. `dy` is the search range on the axis along which two tiles overlap (might be X or Y). `dx` is the search range on the axis which is orthogonal to the first one. So, for two tiles that touch each other horizontally, `dx` is actually vertical and `dy` horizontal. 

I think that makes sense. For instance, one of the tiles above has these params:
 - `dx: 55` 
 - `dy: 23`
 - `axis: 1`
 - `z_frame: 472`

You're saying this has been shifted 23 pixels down, and 55 pixels from the left?

One other point of confusion: Why do `dx` & `dy` increase? I had expected `dx` & `dy` to be similar regardless of whether `--dy` & `--dx` was set to 50, 150, or 300.

Overall though, the software works well and my team is very happy with the alignment quality.

**Comment by gmazzamuto** [comment]
> You're saying this has been shifted 23 pixels down, and 55 pixels from the left?

No, I agree that the nomenclature is misleading, but in that context `dx`, `dy` and `dz` are just the coordinates of the peak in the 3D cross-correlation map. For the real shifts, one has to take into account the overlap and the max shift. For your (and my...) reference, the line that does this is [this one](https://github.com/lens-biophotonics/ZetaStitcher/blob/cb4f14e64bcd0d1dceb9769469f3d69e02b25d74/zetastitcher/align/xcorr_filematrix.py#L50). The reason why the values increase is because the size of the cross-correlation map depends on the overlap but also on the search range. If the overlap is `overlap` and the search range is `max_dy`, then the height of the map is `overap + max_dy` (taken at the **bottom** of the image, i.e. where the tiles overlap). But the coordinate of the peak is relative to the **top-left corner** of the map, so that's why you get different values for different map sizes.

> Overall though, the software works well and my team is very happy with the alignment quality.

That's great to hear! We are also using the software in production on a daily basis, but it is still under active development.. so expect some changes (possibly even breaking changes). And I also hope to publish it as a paper soon. As for the alignment, we also observe good quality, at least with images that are of good quality from the start.. After all, the alignment algorithm is not that much sophisticated (it just finds the maximum in the cross-correlation map).

**Comment by Modjular** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/8238329/121448651-f3358300-c94c-11eb-9a8b-e952b126da83.png)

Is this what I should be picturing? (Sorry you'll have to zoom in to read the text)

**Comment by gmazzamuto** [comment]
![text20030](https://user-images.githubusercontent.com/18688794/121605910-81912e00-ca4d-11eb-9eff-b737c16a31f3.png)

This is what happens under the hood. The orange area of tile B is moved within the yellow area of tile A, which is bigger. The size of the orange area is `(overlap - dy, tile_height)`. The size of the yellow area is `(overlap + dy, tile_height + 2 * dx)`. The size of the cross correlation map is therefore `(2 * dy, 2 * dx)`.

If you have any comments just let me know.

**Comment by Modjular** [comment]
Thanks so much, this cleared things up!
