### ISSUE TITLE
Stage Coordinates

### ISSUE THREAD

**Issue by noamgannot** [lens-biophotonics/ZetaStitcher#2]
How are the stage coordinates of the files determined ?

According to the tutorial, the files should be named using the following convention: X_Y.tiff. If that is the case, where does the z plane of the image come in ?

**Comment by gmazzamuto** [comment]
Hi,

the X_Y.tiff files are actually supposed to be stacks of images, i.e. 3D tiles. The stitching process _does_ compute alignments and displace adjacent tiles along the stack depth (Z), in addition to X and Y. However at the moment you can't have multiple layers of stacks along Z, if that's what you mean (that's why the Z coordinate of each stack is unnecessary). Unfortunately this is not yet supported. You can only stitch a single layer of 3D stacks (that is to say a 2D mosaic of 3D tiles -- say, 12 tiles along X and 15 tiles along Y).
